---
title: "Curriculum Vitae"
---

# Education

**PhD.** Forestry, University of British Columbia, February 2022 - August 2025 (expected completion)

**MSc.** Environmental Studies, University of Victoria, September 2019 - August 2021

**BSc.** Geography & Statistics minor (Honours with distinction), September 2015 - April 2019

# Publications

(7 total, citations = 60, h-index = 5)\
Google scholar: https://scholar.google.com/citations?user=cieOQPYAAAAJ

1.  **Travers-Smith, H**., Coops, N.C., Lantz, T.C., Hamp, M., Ignace, D. & Wulder, M.A. (2024). Vegetation structure and soil organic carbon storage across northern forest-tundra ecotones in continuous permafrost. *Arctic Science*. https://doi.org/10.1139/as-2024-0048.

2.  **Travers-Smith, H.**, Coops, N.C., Mulverhill, C., Wulder, M.A, Ignace, D & Lantz, T.C. (2024). Mapping vegetation height and identifying the northern forest limit across Canada using ICESat-2, Landsat time series and topographic data. *Remote Sensing of Environment.* (Phd thesis). https://doi.org/10.1016/j.rse.2024.114097.

3.  Olthof, I., Fraser, R. H., van der Sluijs, J., & **Travers-Smith, H.** (2023). Detecting long-term Arctic surface water changes. *Nature Climate Change*, 13(11), Article 11. DOI:10.1038/s41558-02301836-9.

4.  **Travers-Smith, H.,** Lantz, T.C., Fraser, R.H., & S.V. Kokelj. (2022). Changes in surface water dynamics across Northwestern Canada are influenced by wildfire and permafrost thaw. *Environmental Research Letters*. DOI:10.1088/1748-9326/ac97f7. (MSc thesis).

5.  **Travers-Smith, H.,** Lantz, T.C., Fraser, R.H. (2021). Surface Water Dynamics and Rapid Lake Drainage in the Western Canadian Subarctic. *Journal of Geophysical Research: Biogeosciences.* DOI:10.1029/2021JG006445. (MSc thesis).

6.  **Travers-Smith, H.,** Giannini, F., Sastri, A., Costa, M. (2021). Estimating chlorophyll-a concentration from fluorescence measurements aboard ships of opportunity. *Frontiers in Marine Science*. DOI: 10.3389/fmars.2021.686750. (BSc honours thesis).

7.  **Travers-Smith, H.,** Lantz, T.C. (2020). Leading edge disequilibrium in sub-Arctic alder and spruce populations. *Ecosphere.* 11,7. DOI: 10.1002/ecs2.3118. (BSc directed study).

# Presentations

**Travers-Smith, H**, Coops, N.C., Mulverhill, C., Wulder, M.A., Ignace, D. & Lantz, T.C. (2024). Changes in vegetation structure across the forest-tundra ecotone using satellite remote sensing. **ArcticNet Annual Scientific Meeting**. Ottawa, Canada. December 2024. Oral presentation.

**Travers-Smith, H**, Coops, N.C., Mulverhill, C., Wulder, M.A., Ignace, D. & Lantz, T.C. (2024). Mapping vegetation height and identifying the northern forest limit across Canada. **Canadian Symposium of Remote Sensing**. Halifax, Canada. June 10-13. Student competition, oral presentation.

**Travers-Smith, H**, Coops, N.C., & Lantz, T.C. (2022) Using spaceborne LiDAR to map canopy height across the forest-tundra ecotone. **ArcticNet Annual Scientific Meeting**. Toronto, Canada. December 4-9. Poster.

**Travers-Smith, H**, Coops, N.C., & Lantz, T.C. (2020). Terrain Factors Mediate Change in Sub-Arctic Lakes. **ArcticNet Annual Scientific Meeting**. Online. Poster.

# Awards

**Total PhD funding: \$243,000 (2022-2024)\
Total MSc funding: \$47,500 (2019-2020)**

-   Canadian Society for Remote Sensing Award – Conference Travel, **2024,** \$3,000

-   NSERC - Canada Graduate Scholarships — Doctoral (CGS D), **2022**, \$120,000

-   University of British Columbia – Four Year Doctoral Fellowship, **2022**, \$120,000 

-   NSERC - Canada Graduate Scholarships — Masters (CGS M), **2020**, \$17,500

-   W. Weston Family Award, **2020**, \$15,000

-   BC Graduate Scholarship, **2019**, \$15,000

-   NSERC Undergraduate Student Research Award, **2019, 2018**

-   Jamie Cassels Undergraduate Research Award, **2018**

-   Maureen McLeod Scholarship in Geography, **2018**

-   Mr & Mrs. John L. Wyatt Price Scholarship in Geography, **2018**

-   University of Victoria President's Scholarship, **2018**
